### PR TITLE
Added a design md for the ui flow for minting svg as nft

### LINKED ISSUE #7: Design minting flow UX/UI
### Increasing Access

The minting flow UX/UI is critical for ensuring that users have a smooth, intuitive, and pleasant experience when minting their SVGs as NFTs on Starknet. 

### Feature enhancement details

This involves designing the user interface elements and interaction patterns that guide the user through the entire minting process, from creating SVGs to finalizing the mint as an NFT. A well-designed UX/UI will reduce friction, minimize user errors, and enhance overall satisfaction with the platform.

### PR DESCRIPTION
**Pull request by Ugo-X**
closes #7 

Changes:

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] has no test errors (`npm run test`)
* [ ] is from a uniquely-named feature branch and is up to date with the  `develop` branch.
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Comment by caseywescott** [comment]
Hey @Ugo-X - Looking good so far! We are clarifying the cairo contract right now...Here is the latest draft getting worked on to inform the UI/UX: https://github.com/cienicera/nft-svg-onchain-multiseries/issues/4#issue-2486339988

Let me know if you have any questions or thoughts and I can work with you!

**Key Elements to Design:**

**Series Management:**

**Series Creation:** Interface to create a new series, capturing details like name, description, artist metadata, and base URI.

**Series Details:** Display of existing series with associated metadata and a list of NFTs in each series.
Artist Management:

**Artist Metadata:** Allow users to input and view artist information within the context of a series. Consider if artist data should be managed separately or within the series struct (open to suggestions).
Token Management:

**Minting NFTs:** Interface for minting new NFTs within a specific series, including selecting the series, entering token metadata (e.g., token URI), and managing ownership.

**Token Details:** Display of NFT details within a series, including ownership and metadata.
Mapping and Management:

**Rough Mint Function worklfow:**

Provide a clear and intuitive UI flow for the minting process, ensuring that users can understand how to add NFTs to a series and see the result of their actions.

**Considerations:**

The design should reflect the contract's logic and make it easy for users to manage multiple series and NFTs within those series.

The interface should be intuitive, even for users who are not familiar with the underlying smart contract mechanics.
Please think through the TokenData structure and how best to display and manage this data in the UI. If you have ideas for improving the contract's structure from a UI/UX perspective, we’re open to suggestions.

If you can flesh this out into a good UI/UX for these technical requirements that would be awesome!!

**Review by caseywescott — COMMENTED** [review]
Looks good to me! When you mean section - does that mean a popup?

**Comment by Ugo-X** [comment]
Yes a popup/modal

**Comment by caseywescott** [comment]
Cool this all looks good. I may have some more questions on this so I might keep it open but this is damn near resolved - I just want to allow the dev implementing this to be able to ask questions for clarification. Cool?

**Comment by Ugo-X** [comment]
> Cool this all looks good. I may have some more questions on this so I might keep it open but this is damn near resolved - I just want to allow the dev implementing this to be able to ask questions for clarification. Cool?

Yes it's cool chief

**Comment by caseywescott** [comment]
Amazing Ugo! Thanks so much for vision boarding the UI/UX ! Will be implementing these details ASAP

**Pull request merged**
