### PR TITLE
feat: Implement mint button

### LINKED ISSUE #6: Implement mint button in UI and text fields for Series and Artist Metadata
This button will allow users to mint their generated SVGs as NFTs on Starknet directly from the p5.js Web Editor interface. The implementation of this button involves designing the user interface, integrating with the Starknet blockchain, and providing real-time feedback on the minting process. This feature should Also include text fields for users to submit both Series and Artist metadata when initiating the minting process. These fields will capture crucial information required for creating and organizing NFT series.

### Feature request details

Tasks:

Design the Mint Button UI:

Create a visually appealing and intuitive "Mint" button and text fields that fits seamlessly with the existing design of the p5.js Web Editor.
Consider adding a label or tooltip that explains the button's function to users unfamiliar with blockchain or NFT terminology.
Position the Mint Button:

Decide where to place the "Mint" button within the editor’s UI. It should be easily accessible and clearly associated with the SVG output area.
Ensure the button is not intrusive and does not clutter the interface.
Integrate with Starknet SDK:

Use the Starknet JavaScript SDK to interact with the smart contract responsible for minting the SVGs as NFTs.
Implement the logic to capture the SVG data generated by the user and prepare it for minting when the button is clicked.
Handle User Authentication:

Ensure that users are authenticated and connected to their Starknet wallet before allowing them to mint an NFT.
If the user is not authenticated, prompt them to connect their wallet first. Integrate a wallet connection flow that triggers when the user clicks the "Mint" button if they aren't already connected.
Minting Process Workflow:

When the "Mint" button is clicked:
Collect the SVG data from the user's current p5.js sketch.
Call the appropriate function in the Starknet smart contract to mint the SVG as an NFT.
Pass any necessary parameters to the contract, such as metadata, recipient address, or other custom settings.
Real-Time Feedback and Notifications:

Provide real-time feedback during the minting process. Display a loading spinner or progress bar to indicate that the transaction is being processed.
Notify the user when the transaction is successfully completed, showing the transaction hash and a link to view the NFT on a blockchain explorer.
If the transaction fails, display an error message with possible reasons for the failure and suggestions for resolving the issue.
Transaction Confirmation:

After the minting transaction is sent to Starknet, wait for confirmation. Use the Starknet SDK to monitor the transaction status and provide updates to the user.
Once confirmed, update the UI to reflect that the NFT has been successfully minted.
Post-Minting Actions:

Consider providing users with additional options after minting, such as downloading the SVG, sharing the NFT on social media, or viewing the NFT in their wallet.
Update any relevant UI elements or logs to keep a record of minted NFTs.

### PR DESCRIPTION
**Pull request by Benjtalkshow**
Fixes #6

Changes:

I have verified that this pull request:

* [ ] has no linting errors (`npm run lint`)
* [ ] has no test errors (`npm run test`)
* [ ] is from a uniquely-named feature branch and is up to date with the  `develop` branch.
* [ ] is descriptively named and links to an issue number, i.e. `Fixes #6`

### This feature introduces a "Mint NFT" button to the `p5.js` Web Editor interface.
 - The button is strategically placed on the toolbar to ensure easy access without cluttering the interface.
 -  A Mint NFT modal has been designed according to the user flow outlined in the other issue, including input fields for Series and Artist metadata.
 -  User authentication has been implemented using the `Starknet SDK` , prompting users to connect their wallet before minting.
 - Since the smart contract for minting is currently unavailable, the functionality for capturing SVG data and initiating the minting process has not been implemented yet. Watch the demo video below to see the current progress. Once the contract is ready, the minting functionality will be completed, along with real-time feedback for users during the transaction process.

[Screen Recording - Made with FlexClip (4).webm](https://github.com/user-attachments/assets/0c6a7ab9-c611-452b-9ba6-ef2cec7628e5)

### CODE REVIEW

**Comment by caseywescott** [comment]
Hey @Benjtalkshow - This looks great! That said, something about your PR deletes a previous feature: WalletConnect - Pic Attached. Can you ensure that the previous feature is intact on your commits? Looks awesome though!
walletconnect

**Comment by Benjtalkshow** [comment]
@caseywescott 
Reverted the `Connect Wallet` feature
Demo below:

[Screen Recording - Made with FlexClip (4).webm](https://github.com/user-attachments/assets/9f438c82-8c19-48de-8677-35931941a5ed)

**Comment by caseywescott** [comment]
the app crashes for me - attached pic...Also, why are we using mongoose or something calling a MongoDB ?
error_log_commit2

**Comment by Benjtalkshow** [comment]
> the app crashes for me - attached pic...Also, why are we using mongoose or something calling a MongoDB ? error_log_commit2

@Benjtalkshow 
You have to make sure your mongoDB is running as a service on your machine. That's how to start the app. You can confirm from Ugo-X

**Comment by caseywescott** [comment]
This looks great! Thanks so much @Benjtalkshow !!!

**Pull request merged**
